apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "swingletree.fullname" . }}
  labels:
    app: {{ template "swingletree.name" . }}
    chart: {{ template "swingletree.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "swingletree.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "swingletree.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-config
        - name: appkey
          secret:
            secretName: {{ .Release.Name }}-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.redis.password }}
          - name: STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-config
                key: redis-credential
          {{ end }}
          volumeMounts:
            - name: config
              mountPath: /opt/swingletree/swingletree.conf.yaml
              subPath: swingletree.conf.yaml
              readOnly: true
            - name: appkey
              mountPath: /opt/swingletree/gh-app.pem
              subPath: gh-app.pem
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
