apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
stringData: 
  swingletree.conf.yaml: {{ toYaml .Values.swingletree | quote }}
  gh-app.pem: {{ .Values.github_app_key | quote }}
  {{ if .Values.redis.password }}
  redis-credential: {{ .Values.redis.password }}
  {{ end }}