# Swingletree HELM configuration

## ElasticSearch configuration (history not available if disabled)
elastic:
  enabled: false
  node: http://localhost:9200
  index: swingletree
  auth: # elastic nodejs auth object
    username:
    password:
    apiKey:

## Redis configuration
redis:
  password: # set your database password with this value

  # redis helm dependency configuration ---
  enabled: true # enables the redis helm dependency chart
  cluster:
    enabled: false
  fullnameOverride: swingletree-cache
  image:
    registry: docker.io # set this to your procy registry, if you have no direct access to GitHub Package Registry (mosty in enterprise environments)
  persistence:
    enabled: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false

# cookie settings
cookies:
  secure: true # use secure cookies (https on ingress required)

# jwt settings used by deck
jwt:
  secret: # if you do not set this a random secret will be generated on startup of deck (not compatible when running more than one deck instance)

## GitHub configuration
github:
  app:
    id: # The AppId of your GitHub app instance (not installation!)
    page: # the GitHub App public page. Will be referenced in the Swingletree landing page.
    keyfile: gh-app.pem # the key file of your GitHub App (you retrieve this from the App settings page)
  base: https://api.github.com # Github Api base url
  secret: # this is the github app webhook secret. You should set it
  clientID: # client id of the github app
  clientSecret: # client secret of the github app
  authorizationURL: https://github.com/login/oauth/authorize # adjust this, if you are running GitHub Enterprise
  tokenURL: https://github.com/login/oauth/access_token # adjust this, if you are running GitHub Enterprise
  userProfileURL: https://api.github.com/user # adjust this, if you are running GitHub Enterprise
  callbackURL: http://localhost:3020/auth/github/callback # adjust this, if you are running GitHub Enterprise
  debug: false # runs octokit in debug mode. Use this only for debug, since this can reveal secret tokens in the logs!

## SonarQube configuration
sonar:
  base: # SonarQube base url
  token: # SonarQube Server API token

## Feature flags
features:
  login: true # enable authentication via github for deck
  yoke: https://github.com/swingletree-oss/yoke/releases # yoke download url

## Swingletree core service configuration
### deck configuration
deck:
  path: # set this to the reverse proxy path, if deck is running behind a path in a reverse proxy

### gate configuration
gate:
  api:
    token: # authentication secret for gate plugin endpoints. Set this to a value.

### scotty configuration
scotty: # not needed yet :)


# github app key file content
github_app_key: # set using the bake.sh option --gh-keyfile or via --set-file when using HELM

## Plugin configuration
plugins:
  nebula:
    enabled: true
    context: gradle/nebula
    insecure: false # disable authentication for this plugin endpoint
  zap:
    enabled: true
    context: security/zap
    insecure: false # disable authentication for this plugin endpoint
  twistlock:
    enabled: true
    context: security/twistlock
    insecure: false # disable authentication for this plugin endpoint
  sonar:
    enabled: true
    context: sonarqube
    insecure: false # disable authentication for this plugin endpoint
  testng:
    enabled: true
    context: test/testng
    insecure: false # disable authentication for this plugin endpoint

# ingress configuration
ingress:
  enabled: true
  deck:
    path: /
    hosts:
      - swingletree.minikube
  gate:
    path: /
    hosts:
      - gate.swingletree.minikube

  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  tls: []


#######################################################################################
# Advanced section
#--------------------------------------------------------------------------------------

replicaCount: 1

# Custom CA to trust
certificates:
  ca:
    enabled: false # use custom CA
    value: # CA certificate contents (use bake.sh option --custom-ca-file to set this on bake)


# images to use for this deployment
images:
  deck:
    repo: deck/deck
    version: 1.4.6                 #deck_VERSION
  gate:
    repo: gate/gate
    version: 1.4.2                 #gate_VERSION
  scotty:
    repo: scotty/scotty
    version: 1.1.3                 #scotty_VERSION
  plugin-nebula:
    repo: plugin-nebula/plugin-nebula
    version: 1.2.2                 #plugin-nebula_VERSION
  plugin-sonarqube:
    repo: plugin-sonarqube/plugin-sonarqube
    version: 1.1.4                 #plugin-sonarqube_VERSION
  plugin-twistlock:
    repo: plugin-twistlock/plugin-twistlock
    version: 1.1.2                 #plugin-twistlock_VERSION
  plugin-zap:
    repo: plugin-zap/plugin-zap
    version: 1.1.2                 #plugin-zap_VERSION
  plugin-testng:
    repo: plugin-testng/plugin-testng
    version: 1.1.0                 #plugin-testng_VERSION
pullPolicy: IfNotPresent
registry: docker.pkg.github.com/swingletree-oss/ # set this to your procy registry, if you have no direct access to GitHub Package Registry (mosty in enterprise environments)

# configure your image pull secret if you need to pull from a private registry
#imagePullSecret: regcred

# default service configuration
service:
  type: ClusterIP
  port: 3000

# log level of all swingletree pods
log:
  level: info

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
