version: "3.3"

services:

# --- CORE SERVICES

  deck:
    container_name: deck
    env_file:
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/deck:1.7.0                                 #deck_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/deck/swingletree.conf.yaml
    ports:
      - "3000:3000"
  scotty:
    container_name: scotty
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/scotty/scotty:1.3.0                        #scotty_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/scotty/swingletree.conf.yaml
      # mount github key file if required
      # - /path/to/gh-app.pem:/opt/scotty/gh-app.pem
    expose:
      - "3000"
  gate:
    container_name: gate
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/gate/gate:1.5.0                            #gate_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/gate/swingletree.conf.yaml
    ports:
      - "3001:3001"

  redis:
    container_name: redis
    image: redis
    logging:
      driver: none
    expose:
      - "6379"


# --- PLUGIN SERVICES

  plugin-nebula:
    container_name: plugin-nebula
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/plugin-nebula/plugin-nebula:1.2.5          #plugin-nebula_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/plugin-nebula/swingletree.conf.yaml
    expose:
      - "3000"

  plugin-sonarqube:
    container_name: plugin-sonarqube
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/plugin-sonarqube/plugin-sonarqube:1.1.7    #plugin-sonarqube_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/plugin-sonarqube/swingletree.conf.yaml
    expose:
      - "3000"

  plugin-twistlock:
    container_name: plugin-twistlock
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/plugin-twistlock/plugin-twistlock:1.1.6    #plugin-twistlock_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/plugin-twistlock/swingletree.conf.yaml
    expose:
      - "3000"

  plugin-zap:
    container_name: plugin-zap
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/plugin-zap/plugin-zap:1.1.6                #plugin-zap_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/plugin-zap/swingletree.conf.yaml
    expose:
      - "3000"

  plugin-junit:
    container_name: plugin-junit
    env_file: 
      - ./compose.env
    environment: []
    image: docker.pkg.github.com/swingletree-oss/plugin-junit/plugin-junit:1.0.2            #plugin-junit_VERSION
    restart: always
    volumes:
      - ./swingletree.conf.yaml:/opt/plugin-junit/swingletree.conf.yaml
    expose:
      - "3000"


# --- AUXILIARY COMPONENTS

## -- Elasticsearch instance
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    logging:
      driver: none
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    expose:
      - "9200"
      - "9300"


## -- Gitea instance
#  gitea:
#    container_name: gitea
#    image: gitea/gitea:1.12
#    logging:
#      driver: none
#    environment:
#      - USER_UID=1000
#      - USER_GID=1000
#    ports:
#      - "8080:3000"
#    expose:
#      - "3000"

## -- Kibana instance
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.3.1
#    logging:
#      driver: none
#    environment:
#      ELASTICSEARCH_HOSTS: http://elastic:9200
#    ports:
#      - "5601:5601"
#    expose:
#      - "5601"

## -- Grafana instance
#  grafana:
#    container_name: grafana
#    image: grafana/grafana
#    logging:
#      driver: none
#    ports:
#      - "9000:9000"
#    expose:
#      - "9000"
