apiVersion: apps/v1
kind: Deployment
metadata:
  name: swing-scotty
  labels:
    app: scotty
    chart: {{ template "swingletree.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scotty
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: scotty
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-config
        - name: appkey
          secret:
            secretName: {{ .Release.Name }}-config
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry }}{{ .Values.images.scotty }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            {{ if .Values.redis.enabled }}
            - name: SCOTTY_STORAGE_HOST
              value: "{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}"
            {{ end }}
            {{ if .Values.redis.password }}
            - name: SCOTTY_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-config
                  key: redis-credential
            {{ end }}
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
          volumeMounts:
            - name: config
              mountPath: /opt/scotty/swingletree.conf.yaml
              subPath: swingletree.conf.yaml
              readOnly: true
            - name: appkey
              mountPath: /opt/scotty/gh-app.pem
              subPath: gh-app.pem
          ports:
            - name: http
              containerPort: {{ .Values.swingletree.scotty.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
