apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-zap
  labels:
    app: plugin-zap
    chart: {{ template "swingletree.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: plugin-zap
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: plugin-zap
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-config
        - name: appkey
          secret:
            secretName: {{ .Release.Name }}-config
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry }}{{ .Values.images.plugin.zap }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: ZAP_URLS_SCOTTY
              value: "http://swing-scotty.{{ .Release.Namespace }}:{{ .Values.swingletree.scotty.port }}"
            - name: SCOTTY_CLIENT_URL
              value: "http://swing-scotty.{{ .Release.Namespace }}:{{ .Values.swingletree.scotty.port }}"
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
          volumeMounts:
            - name: config
              mountPath: /opt/plugin-zap/swingletree.conf.yaml
              subPath: swingletree.conf.yaml
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.swingletree.zap.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
