apiVersion: apps/v1
kind: Deployment
metadata:
  name: swing-deck
  labels:
    app: deck
    chart: {{ template "swingletree.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deck
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: deck
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: swingletree-config
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry }}{{ .Values.images.deck.repo }}:{{ .Values.images.deck.version }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.log.level }}
            {{- if .Values.certificates.ca.enabled }}
            - name: NODE_EXTRA_CA_CERTS
              value: /opt/cert/ca.pem
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/deck/swingletree.conf.yaml
              subPath: swingletree.conf.yaml
              readOnly: true
            {{- if .Values.certificates.ca.enabled }}
            - name: config
              mountPath: /opt/cert/ca.pem
              subPath: ca
              readOnly: true
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
