{{- $config := include "swingletree.config" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: swingletree-config
type: Opaque
stringData: 
  swingletree.conf.yaml: {{ $config | quote }}
  gh-app.pem: {{ .Values.github_app_key | quote }}
{{- if .Values.certificates.ca.enabled }}
  ca: {{ .Values.certificates.ca.value | quote }}
{{ end }}