#remote_theme: error418/Twenty-Jekyll-Theme
remote_theme: error418/jekyll-doc-theme

title: Swingletree
email: 
description:  >-
  Simplify your build feedback
lang: de-DE

logo: assets/images/icon.svg

baseurl: "/swingletree" # the subpath of your site, e.g. /blog/
url: "https://swingletree-oss.github.io" # the base hostname & protocol for your site
git_address: https://github.com/swingletree-oss/swingletree
git_edit_address: https://github.com/swingletree-oss/swingletree/blob/master/docs

blog:
  enable: false

css:
  extra:
    - /assets/css/swingletree.css

sass:
  style: compressed

# cookies opt in
optin:
  notice: We are using Cookies and Google Analytics to make this website better
  accept: Got it!
  decline: Decline

analytics:
  enable: true
  id: UA-111350981-3

head:
  include: head-ext.html

nav:
  - id: showcase
    url: /showcase.html
    name: Showcase
  - id: support
    url: /support.html
    name: Support

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
#  posts:
#    permalink: /blog/:year/:month/:day/:title/
#    output: true
