name: Semantic Release

on:
  push:
    branches:
    - "master"

jobs:
  release:
    container:
      image: node:10-alpine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Git
      run: apk add git
    - name: Initialize
      run: npm i
    - name: Release Codebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_SECRET }}
      run: npm run release
