name: Semantic Release

on:
  push:
    branches:
    - "master"

jobs:
  release:
    runs-on: alpine/helm:2.16.1
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1
      with:
        node-version: '13.x'
    - name: Install Git
      run: apk add git
    - name: Initialize
      run: npm i
    - name: Release Codebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_SECRET }}
      run: npm run release
