name: Semantic Release

on:
  push:
    branches:
    - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.1.1
    steps:
    - uses: actions/checkout@v1
    - name: Install Git
      run: apk add --no-cache git nodejs nodejs-npm
    - name: Initialize
      run: npm i
    - name: Release Codebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run release
